### ISSUE TITLE
Lab 4 - Improve the aesthetics with a bounding box Step 4 

### ISSUE THREAD

**Issue by AhmedRashwanASU** [DS4PS/cpp-529-spr-2021#10]
I have selected **WASHINGTON city** as below, how can I get the correct "xmin " ,  "ymin " ,  "ymax " ,  "ymin " Values ? In order to get the desired view ?

![image](https://user-images.githubusercontent.com/77247268/113191750-f76b6300-926e-11eb-9449-3e33a597d967.png)

```{r , eval=TRUE}
# user-defined bounding box to move slocer to subjects 
bb <- st_bbox( c( xmin =  -10451823, xmax = -10324525, 
                  ymax = 5639769, ymin = 5491665 ), 
               crs = st_crs("+init=epsg:3395"))

tm_shape( msp_dorling, bbox=bb ) + 
  tm_polygons( col="hinc12", n=10, style="quantile", palette="Spectral" ) +
  tm_layout( "Dorling Cartogram", title.position=c("right","top") )
```

![image](https://user-images.githubusercontent.com/77247268/113192362-b58eec80-926f-11eb-9b7a-f04de22e3844.png)

**Comment by lecy** [comment]
Try the locator() function if you are on a PC (it doesn't work on macs unfortunately): 

https://user-images.githubusercontent.com/1209099/98859048-cf45a980-241e-11eb-929d-7baeae14f989.gif

You can **NOT** place locator() into an RMD file because it is an interactive function. 

You can use it to quickly determine the coordinates for the bounding box, though. 

Otherwise you can use these to add the latitude and longitude coordinates for your map, or print your current bounding box using the graphics parameters **par()** function:

```
axis( side=1 )
axis( side=2 )
par( "usr" )
```

And based upon the values make some judicious guesses.

**Comment by AhmedRashwanASU** [comment]
Thank you Prof That's Perfect!
