### ISSUE TITLE
Lab 04 - Getting an error message in Step 4

### ISSUE THREAD

**Issue by ellihammons21** [DS4PS/cpp-529-spr-2021#11]
In step 4, when trying to transform the shapefile into a Dorling cartogram, the following line of code is producing the error shown below:

sanfran.sp <- as_Spatial( sanfran )

Error in h(simpleError(msg, call)) : error in evaluating the argument 'x' in selecting a method for function 'addAttrToGeom': subscript out of bounds

Any ideas what is causing this error, and how to fix it?
@Anthony-Howell-PhD @lecy

**Comment by Anthony-Howell-PhD** [comment]
Hi @ellihammons21.  Its tough to say without seeing your RMD file, but I would like to note that it seems one line of code no longer works properly (after updating to a newer R version than when the Lab was originally created.)  The error relates to the piped commands after the get_acs() function just before step 3. 

In the older Rstudio versions, I could run the following code without error.  

```
msp.pop1 <-
get_acs( geography = "tract", variables = "B01003_001",
         state = "55", county = county.fips[state.fips=="55"], geometry = TRUE ) %>%
         select( GEOID, estimate ) %>%
         rename( POP=estimate )

```
After updating Rstudio, this no longer works due to the rename(Pop=estimate) command.  I went back and updated the code to the following, which now works without problem. 

```
msp.pop1 <-
get_acs( geography = "tract", variables = "B01003_001",
         state = "27", county = county.fips[state.fips=="27"], geometry = TRUE ) %>%
         select( GEOID, "POP"=estimate ) 

```

Not that you will have to make the same change for `msp.pop2` also. 

Give that a try, and let me know if it solves your problem. If it doesn't solve your problem, please attach your RMD source file or email it to me: Anthony.howell@asu.edu)

**Comment by ellihammons21** [comment]
I tried that, but still getting the same error code. I will go ahead and send you the RMD source file via email. Thanks!

**Comment by scribenaz** [comment]
found this that helped me and it worked.
https://github.com/DS4PS/cpp-529-spr-2020/issues/9

**Comment by ellihammons21** [comment]
@scribenaz 

That worked! Thank you for the suggestion.
